name: oidc-exchange action
description: Exchange GitHub Actions identity tokens with short-lived service tokens

inputs:
  token-server:
    description: Server responsible for exchanging GitHub tokens
    required: true
  service:
    description: Service to request a token for
    required: true
  silo: 
    description: URL of the silo to request access to. Valid only when the service is oxide.
  duration: 
    description: Maximum duration of the token. Valid only when the service is oxide.
  repositories:
    description: Comma-separated list of repository names. Valid only when the service is github.
  permissions:
    description: Comma-separated list of permissions. Valid only when the service is github.
  configure-git:
    description: Configure git to use the GitHub token for HTTPS operations. Valid only when the service is github.
  configure-env:
    description: Configure the environment variables to authenticate with the service.

outputs:
  access-token:
    description: The access token obtained from the token server

runs:
  using: node20
  main: dist/index.js
