name: Oxide OIDC Exchange
description: Exchange GitHub Actions identity tokens for Oxide access tokens

inputs:
  token-server:
    description: Server responsible for exchanging GitHub tokens for Oxide access tokens
    required: true

outputs:
  access-token:
    description: The access token obtained from the token server

runs:
  using: node20
  main: dist/index.js
